### ISSUE TITLE
Planning - Part 1

### ISSUE THREAD

**Issue by jamen** [soundcove/info#1]
- [x] <s>Language and Framework?</s>: NodeJS
 - [x] <s>Open source or closed source?</s>: Open source
 - [x] Business plan
   - [x] <s>Revenue...</s> Advertisements.  Paid plans are too early right now (might possibly come in a later plan).
   - [x] <s>Tracking costs...</s>  We're quite early in this product, tracking costs and revenue will be in a later plan.
   - [x] <s>Resources...</s>
     - 2 VPS's
     - Domain
     - Brand assets.
   - [x] <s>Sponsorships...</s>  Decided as something we don't need to focus on yet.
   - [x] <s>Registering business?</s> Something to focus on in the future.
   - (Others?)

 - [x] Structure
   - [x] <s>Testing...</s>  See the flowchart below, this isn't worrisome now.
   - [x] <s>Deployment...</s>  Continuous integration
   - [x] <s>Modular...</s> See flowchart below.

 - [x] Security
   - [x] <s>SSL?</s> Yes.
   - [x] <s>Research WebSockets over SSL.</s> WSS (WebSockets Secure, WebSockets over TLS/SSL)
   - [x] <s>Database?</s> PostgreSQL.
   - [x] <s>Redis?</s> Not with our current resources, perhaps something we would do in the future.
   - [x] <s>Optimize templating to be XSS-proof.</s> Templating wont be likely with our new plan. (See flowchart below)

- [x] Marketing / Design
   - [x] <s>Logo.</s> Find someone capable of making a unique logo that makes our service recognizable.
   - [x] <s>Advertise our service? (The business plan should be kept in mind here)</s> Possibly through YouTube to music producers and listeners, as well as SoundCloud.
   - [x] <s>Key points and ideas to market.</s> Market to producers and listeners on YouTube 

---

Service flow:

![image](https://cloud.githubusercontent.com/assets/6251703/10556991/370516b6-7455-11e5-861f-176a2beae3bd.png)

**Comment by JelaniThompson** [comment]
Noice

**Comment by Prestonion** [comment]
Looks pretty dank.

**Comment by programmatical** [comment]
- [x] <s>Language and Framework?</s>: NodeJS
 - [x] <s>Open source or closed source?</s>: Open source
 - [ ] Business plan
   - [ ] Revenue...  Ads, paid plans, others? 
   - [ ] Tracking costs...  How will we track costs to ensure we aren't wasting money?
   - [ ] Resources...  What needs to be bought?
   - [ ] Sponsorships...  Who, why, and when?
   - [x] Registering business? Shouldn't be something we're focusing on at the beginning of development, can be held until absolutely needed.
   - (Others?)

 - [ ] Structure
   - [ ] Testing...  How will client-side and server-side testing work?
   - [x] Deployment...  How will we deploy the server? (Continuous integration?) CI
   - [ ] Modular...  How will we design it so client and server are separate?

 - [ ] Security
   - [x] SSL? Will buy soon.
   - [ ] Research WebSockets over SSL.
   - [x] Database? PostgreSQL, why? Popular to contrary belief, PostgreSQL excels in both reliability and performance in comparison to MySQL.
   - [ ] Redis?
   - [ ] Optimize templating to be XSS-proof.

- [ ] Marketing / Design
   - [ ] Logo.
   - [ ] Advertise our service? (The business plan should be kept in mind here)
   - [ ] Key points and ideas to market.

**Comment by jamen** [comment]
Updated original post with changes.

**Comment by Prestonion** [comment]
Maybe have donations with the revenue?

**Comment by jamen** [comment]
Nice job everyone, that wraps up Plan 1.
