### ISSUE TITLE
Some placeholder logos?

### ISSUE THREAD

**Issue by jamen** [soundcove/info#3]
I'm bored at school, and since we have access to Photoshop I thought I would whip up a few logos:

![soundcove](https://cloud.githubusercontent.com/assets/6251703/10703131/3b8a7e70-798b-11e5-84ba-83342cf226b9.png)

[soundcove2](https://cloud.githubusercontent.com/assets/6251703/10703129/37bf1d46-798b-11e5-9bd3-7392dc350225.png)

[soundcove3](https://cloud.githubusercontent.com/assets/6251703/10703132/4078065a-798b-11e5-95c8-2ff1ebc8b103.png)

**Comment by melemonsqueezer1** [comment]
I like the first one.
