### ISSUE TITLE
Planning - Part 3: API Structure.

### ISSUE THREAD

**Issue by jamen** [soundcove/info#4]
So, hopefully we're all aware  by now that the whole API server will be based through WebSockets.

But that's all we really have planned.

All I can suggest right now is that we should use JSON to structure the information between the server and client.  I also would like both client and server communications to be based around a similar structure just to unify things and make documentation more simple.

There is lots more we need to plan for this, so feel free to comment anything about the API server below.

Try to reference [Planning - Part 2](2), use the ideas from there to piece together this API system.

**Comment by ProBukkit** [comment]
API Structure:

Client: 
    Description: Initializes client with api server.
    -> Handshake:
            Description: Handshakes with api server.
            -> Authentication:
                 Description: Validates user with api server.

**Comment by jamen** [comment]
Closing this, needs to be discussed more via chat.
